name: rtd312
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - jupyter
  - matplotlib
  - corner
  - tqdm
  - sphinx_rtd_theme
  - nbsphinx
  - ipywidgets
  - sphinx-copybutton
  - pip:
    - git+https://github.com/AlanPearl/diffmahnet.git
    - myst_parser
